# Generated by Django 2.1.2 on 2018-10-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='image',
        ),
    ]
