# Generated by Django 2.1.2 on 2018-10-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_discussion_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='comments',
        ),
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='title', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Discussion'),
        ),
    ]
