# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-25 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181021_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='batch',
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectName',
            field=models.CharField(max_length=10),
        ),
    ]
