# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20181025_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='batch',
            field=models.CharField(default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectName',
            field=models.CharField(max_length=250),
        ),
    ]
