# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-10-25 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20181025_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='batch',
        ),
    ]
