# Generated by Django 2.1.3 on 2018-11-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_subjects_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='discussion',
            name='picture',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectLogo',
            field=models.FileField(upload_to=''),
        ),
    ]
