# Generated by Django 2.1.3 on 2018-11-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181113_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('file', models.FileField(default='', upload_to='')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Subjects')),
            ],
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='like',
            new_name='anonymous',
        ),
        migrations.AddField(
            model_name='comments',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
