# Generated by Django 2.1.3 on 2018-11-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181127_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='discussion',
        ),
        migrations.RemoveField(
            model_name='favourite',
            name='user',
        ),
        migrations.AddField(
            model_name='discussion',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
