# Generated by Django 2.1.3 on 2018-11-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_filefolder_folder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default=5, max_length=100),
            preserve_default=False,
        ),
    ]
