# Generated by Django 2.1.3 on 2018-11-28 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20181128_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='favourite',
        ),
    ]
